version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: thcs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: class_management
      MYSQL_USER: thcs_user
      MYSQL_PASSWORD: thcs_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: thcs_mailpit
    restart: always
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  mysql_data:
